# Generated by Django 3.1.7 on 2021-04-26 16:41

import bboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210419_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[bboard.validators.validate_even], verbose_name='Цена'),
        ),
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published')},
        ),
    ]
